/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function shutdown(): void
export function forceShutdown(): void
export function reboot(): void
export function forceReboot(): void
export function logout(): void
export function forceLogout(): void
export function sleep(): void
export function hibernate(): void
